swagger: "2.0"
info:
  title: "Flashcard API"
  description: "API to manage flashcards"
  version: "1.0"
host: "localhost:5000"  # Update with your actual host
basePath: "/api"
schemes:
  - "http"
  - "https"
paths:
  /flashcards:
    get:
      tags:
        - "flashcards"
      summary: "Get a list of all flashcards"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successfully retrieved flashcards."
        500:
          description: "Server error."

